spring:
    data:
       mongodb:
            uri: mongodb+srv://dalcala:Everis%402021@cluster0.nqzf5.mongodb.net/banco?retryWrites=true&w=majority
    application:
        name: gestion-productos-financieros
    cloud:
      config:
        uri: http://localhost:8081
        username: root
        password: s3cr3t
    boot:
      admin:
        client:
          url: http://localhost:8086
server:
     error:
        include-message: always